require 'rake/testtask'

Rake::TestTask.new(:spec) do |t|
  t.pattern = 'spec/**/*_spec.rb'
end

Rake::TestTask.new(:benchmark) do |t|
  t.pattern = 'spec/**/*_benchmark.rb'
end

task :default => :spec
